version: '3'

services:
  db: 
    image: postgres
  web:
    build: ./web/
    command: python ./web/manage.py runserver 0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

