version: '3.7'

services:

  postgres: 
    restart: always
    image: postgres:latest
    env_file:
      - config/db/postgres_env
    networks:
      - postgres_network
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  django:
    build: django/
    command: gunicorn --bind 0:8000 mysite.wsgi:application
    volumes: 
      - ./django/:/opt/services/django/src
      - static_volume:/opt/services/django/static
      - media_volume:/opt/services/django/media
    depends_on:
      - postgres
    networks:
      - postgres_network
      - nginx_network

  nginx:
    image: nginx:1.13
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/opt/services/django/static
      - media_volume:/opt/services/django/media
    depends_on:
      - django
    networks:
      - nginx_network


networks:
  nginx_network:
    driver: bridge
  postgres_network:
    driver: bridge


volumes:
  postgres_volume: {}
  static_volume: {}
  media_volume: {}